language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt59base qt59tools checkinstall sed
    - source /opt/qt*/bin/qt*-env.sh

script: 
  - mkdir appdir appdir/usr appdir/usr/share appdir/usr/share/applications
  - cp  byteicon.desktop appdir/usr/share/applications
  - qmake PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir install ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - cp /home/travis/build/Bytespeicher/BytespeicherTrayIcon/byteicon appdir/usr/share/applications
  - cp res/byteicon.png appdir/usr/share/applications
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - mkdir deb
  - cd deb
  - qmake ../main.pro
  - echo "BytespeicherTrayIcon" > description-pak
  - checkinstall --install=no -y --pkggroup="Office" --pkgname="byteicon" --pkgversion="0.1" --pkgrelease="0.1" --pkglicense="LGPLv3" --maintainer="test@example.com" --provides="byteicon" --requires="qt59base"
  

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - ls -l
  - curl --upload-file ./byteicon*.AppImage https://transfer.sh/byteicon-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - curl --upload-file ./byteicon*.deb https://transfer.sh/byteicon-git.$(git rev-parse --short HEAD).amd64.deb
